### ISSUE TITLE
configure gitpod

### ISSUE THREAD

**Issue by cascandaliato** [cascandaliato/goto#2]
`.gitpod.Dockerfile`
```dockerfile
FROM gitpod/workspace-mongodb

RUN npm install -g nodemon
```

---

`.gitpod.yml`
```yml
image:
  file: .gitpod.Dockerfile

tasks:
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
    name: mongodb
  - before: cd backend
    init: go mod download
    command: nodemon --watch cmd --signal SIGHUP --exec "go run" cmd/gateway/main.go -port 3030
    openMode: tab-after
    name: backend
  - before: cd frontend
    init: npm install
    command: gp await-port 3030 && echo VUE_APP_BACKEND=$(gp url 3030) >> .env.development.local && npm run serve
    name: frontend
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3030
    onOpen: ignore

vscode:
  extensions:
    
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

vscode:
  extensions:
    - msjsdiag.debugger-for-chrome@4.12.6:IdQBlCQEnixzHAOkHC36ew==
    - octref.vetur@0.24.0:FtNScOJHzSTxcNY6NB60Cg==
    - esbenp.prettier-vscode@5.1.0:M3Ww4EayZWhGCgk49C1Ldw==
    - premparihar.gotestexplorer@0.1.11:DhzL8CT0KN1bzUVh3ZL3rQ==
```
